name: Test compare
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: read

jobs:
  run:
    if: contains(github.event.pull_request.labels.*.name, 'test-compare')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Test compare
        uses: nearform-actions/github-action-test-compare@ec6b7c67cf28d1158d749da193de1440e9243b6a # v1.1.0
        with:
          label: test-compare
          testCommand: 'npm run test:ci'
